version: 0.2

phases:
  pre_build:
    commands:
      - echo "[PRE_BUILD] Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${REPOSITORY_URI}

  build:
    commands:
      - echo "[BUILD] Building Laravel Docker image..."
      - docker build --no-cache -f Dockerfile.deployment -t ${CONTAINER_NAME} .
      - docker tag ${CONTAINER_NAME} ${REPOSITORY_URI}:latest
      - echo "[BUILD] Pushing image to ECR..."
      - docker push ${REPOSITORY_URI}:latest

  post_build:
    commands:
      - echo "[POST_BUILD] Running Laravel migration via ECS RunTask..."
      - echo "[POST_BUILD] Creating new task definition revision..."
      - |
        aws ecs describe-task-definition \
          --task-definition prod-laravel-task \
          --query 'taskDefinition' \
          --output json > task-definition.json
      - |
        jq --arg IMAGE_URI "${REPOSITORY_URI}:latest" \
          '.containerDefinitions[0].image = $IMAGE_URI | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .placementConstraints, .compatibilities, .registeredAt, .registeredBy)' \
          task-definition.json > new-task-definition.json
      - |
        NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://new-task-definition.json \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)
      - echo "New task definition ARN: $NEW_TASK_DEFINITION_ARN"
      
      - echo "[POST_BUILD] Updating ECS service..."
      - |
        aws ecs update-service \
          --cluster arn:aws:ecs:ap-northeast-1:${AWS_ACCOUNT_ID}:cluster/larabel-cluster \
          --service arn:aws:ecs:ap-northeast-1:${AWS_ACCOUNT_ID}:service/larabel-cluster/prod-laravel-task-service-vqkmsvuc \
          --task-definition $NEW_TASK_DEFINITION_ARN
      - echo "[POST_BUILD] Service update initiated"
artifacts:
  files:
    - imagedefinitions.json
